name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    uses: tomasbjerre/.github/.github/workflows/bundle-gradle-plugin-release.yaml@master
    secrets: inherit
